In [1]:
from torch import cuda
cuda.is_available()

True

In [2]:
import torch

In [3]:
print(torch.__version__)

2.3.1+cu118


In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

**PyTorch Tensors**

**Scalar**

In [5]:
#A scalar is a single value
#torch.tensor creates a tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

**Note: The ndim of scalar is 0 since, there is neither a row nor a column nor any axis associated with a tensor**

In [7]:
#Retrieving the number from a scalar
#This basically returns just the element of the scalar with its original data type
scalar.item()

7

**Vectors**

In [8]:
vector = torch.tensor([1, 2])
vector

tensor([1, 2])

In [9]:
vector.ndim

1

**Vector has multiple elements and the above vector has just one axis consisting of elements 1 and 2**

**Matrices**

In [10]:
MATRIX = torch.tensor([[1, 2], [4, 5]])

In [11]:
MATRIX

tensor([[1, 2],
        [4, 5]])

In [12]:
MATRIX.ndim

2

**Matrix is basically a collection of vectors and the above matrix has 2 dimensions or 2 axes**

In [13]:
MATRIX[0]

tensor([1, 2])

In [14]:
MATRIX[1]

tensor([4, 5])

In [15]:
MATRIX[0][0]

tensor(1)

In [16]:
MATRIX[0][1]

tensor(2)

**Note: The above matrix has vectors as its elements so the first index gives the vector index and the 2nd index gives the element within that vector**

**Tensor**

In [17]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [18]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR_1 = torch.tensor([[[[[1, 2, 3, 4], [3, 4, 5, 7]]]]])

In [22]:
TENSOR_1.shape

torch.Size([1, 1, 1, 2, 4])

In [23]:
TENSOR_1.ndim

5

**Note: According to naming conventions scalars and vectors have lowercase variable names while matrices and tensors have uppercase variable names**

**Creating random tensors**

In [24]:
#Creating a random tensor of size (3, 4)
#torch.rand(n_rows, n_cols) creates a random tensor with the specified dimensions
random_tensor = torch.rand(3, 4)

In [25]:
random_tensor

tensor([[0.1476, 0.0569, 0.3561, 0.4593],
        [0.6001, 0.4712, 0.5978, 0.9927],
        [0.2200, 0.9470, 0.0377, 0.2517]])

In [26]:
random_tensor.ndim

2

In [27]:
#Creating a random tensor with similar shape to an image tensor
image_tensor = torch.rand(224, 224, 3)
image_tensor

tensor([[[0.0284, 0.7910, 0.0637],
         [0.6698, 0.0380, 0.1807],
         [0.1528, 0.4487, 0.9413],
         ...,
         [0.8493, 0.6772, 0.7206],
         [0.9543, 0.0951, 0.4624],
         [0.2559, 0.9112, 0.8021]],

        [[0.9182, 0.1437, 0.4703],
         [0.3276, 0.5030, 0.7941],
         [0.1984, 0.2603, 0.0871],
         ...,
         [0.5092, 0.2247, 0.4100],
         [0.5347, 0.6117, 0.0350],
         [0.8243, 0.0555, 0.0935]],

        [[0.0732, 0.5937, 0.3337],
         [0.1545, 0.5126, 0.6636],
         [0.4916, 0.0590, 0.7282],
         ...,
         [0.2522, 0.8548, 0.1404],
         [0.2393, 0.2023, 0.6201],
         [0.0955, 0.1650, 0.8030]],

        ...,

        [[0.8576, 0.4552, 0.2566],
         [0.3805, 0.9262, 0.6918],
         [0.0841, 0.8294, 0.3358],
         ...,
         [0.6437, 0.6459, 0.7741],
         [0.2935, 0.5535, 0.5175],
         [0.8055, 0.4233, 0.3867]],

        [[0.4706, 0.1258, 0.5048],
         [0.9661, 0.7825, 0.8236],
         [0.

In [28]:
image_tensor.ndim

3

In [29]:
image_tensor.shape

torch.Size([224, 224, 3])

**Note: Here the image_tensor has the dimensions width x height x colour_channels**

**Zeros and Ones Tensor**

In [30]:
#torch.zeros(size = (x, y)) creates a tensor with all 0s according to the specified size
zero_tensor = torch.zeros(size = (3, 4))
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
ones_tensor = torch.ones(size = (3, 4))
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
zero_tensor.dtype

torch.float32

In [33]:
ones_tensor.dtype

torch.float32

**By default all the PyTorch tensors have float32 tensors**

**Creating a tensor with a range**

In [34]:
torch.range(0, 10)

/tmp/ipykernel_5719/1045297309.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

**torch.range will be removed in future**

In [35]:
#By default the step count is 1
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
#step parameter is used for specifying the step size
random_ranged_tensor = torch.arange(start = 0, end = 100, step = 2)
random_ranged_tensor

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [37]:
random_ranged_tensor.shape

torch.Size([50])

random_ranged_tensor.ndim

**Creating tensors like**

In [38]:
ten_zeros = torch.zeros_like(input = torch.arange(start = 1, end = 11, step = 1))
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**torch.zeros_like takes in a range of tensor values and creates a tensor with 0s where the number of 0s is equal to the number of elements**

In [39]:
zeros_tensor = torch.zeros_like(input = torch.arange(start = 0, end = 30, step = 2))
zeros_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Tensor Data types**

In [40]:
#Float32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = None)
float_32_tensor

tensor([3., 6., 9.])

In [41]:
float_32_tensor.dtype

torch.float32

**Note: Even if u set the dtype to None it will have the default float32 data type**

**Precision**

1. **Float32:** 1 precision
2. **Float16:** 1/2 precision

**Common tensor datatype errors**
1. Tensors not in right shape
2. Tensors not in right data type
3. Tensors not on right device

**torch.tensor parameters**
1. **Tensor elements:** The elements or values
2. **dtype:** Data type of the elements in the Tensor
3. **device:** The compute device on which the tensor resides
4. **requires_grad:** Whether gradients are required or not

In [42]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [43]:
float_16_tensor.dtype

torch.float16

**Note: torch.type(torch.dtype) can be used to convert a tensor to another data type**

In [44]:
#Demo tensor multiplication
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [45]:
(float_32_tensor * float_16_tensor).dtype

torch.float32

**Note: When a float32 tensor is multiplied with a float16 tensor the resulting product will be a float32 tensor**

In [46]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

**Getting additional info from the tensors**

1. tensor.shape
2. tensor.device
3. tensor.dtype

In [47]:
t1 = torch.rand(3, 4)
print(f'Tensor: {t1}\nData type: {t1.dtype}\nShape: {t1.shape}\nDevice: {t1.device}')

Tensor: tensor([[0.0995, 0.0544, 0.1057, 0.6752],
        [0.8737, 0.4085, 0.0432, 0.5709],
        [0.4685, 0.7488, 0.1069, 0.2504]])
Data type: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


**By default all the tensors will be saved on a CPU**

**Tensor Manipulation**

1. Addition
2. Subtraction
3. Product (element-wise)
4. Division
5. Matrix multiplication

In [48]:
tensor = torch.tensor([1, 2, 3, 4, 5])
tensor + 10

tensor([11, 12, 13, 14, 15])

In [49]:
#Product
tensor * tensor

tensor([ 1,  4,  9, 16, 25])

In [50]:
tensor * 2

tensor([ 2,  4,  6,  8, 10])

In [51]:
tensor - 20

tensor([-19, -18, -17, -16, -15])

In [52]:
#Testing PyTorch inbuilt functions
torch.add(tensor, 10)

tensor([11, 12, 13, 14, 15])

In [53]:
torch.sub(tensor, 20)

tensor([-19, -18, -17, -16, -15])

In [54]:
torch.mul(tensor, tensor)

tensor([ 1,  4,  9, 16, 25])

**Matrix Multiplication**

There are 2 ways of performing multiplication on tensors namely: element-wise and matrix multiplication (dot product)

In [55]:
torch.matmul(tensor, tensor)

tensor(55)

In [56]:
tensor.shape

torch.Size([5])

In [57]:
#manual matrix multiplication
product = 0
for i in range (len(tensor)):
    product = product + tensor[i] * tensor[i]
product

tensor(55)

**2 main rules of Matrix Multiplication**

1. Inner dimensions have to match i.e. the final dim (no of columns) in the first matrix has to match with the no of rows (first dim) of the 2nd matrix
2. The resulting matrix (product) will have the shape that matches the outer dimensions of the original matrices

In [58]:
#Dealing with tensor shape errors
Tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
Tensor_B = torch.tensor([[7, 8], [9, 10], [11, 12]])

torch.matmul(Tensor_A, Tensor_B.mT)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

**Note: mm is short for matmul; mT gives transpose of tensors**

In [59]:
Tensor_B.shape

torch.Size([3, 2])

In [60]:
Tensor_B.mT.shape

torch.Size([2, 3])

**Note: tensor.T also works for getting the transpose of a tensor but it will be deprecated in the future; Therefore, we should use tensor.mT; However for 1-D tensor (vector) .mT doesn't work and .T has to be used**

In [61]:
print(f'Tensor-A: {Tensor_A}')
print(f'Tensor-B: {Tensor_B}')
print(f'Shape of Tensor-A: {Tensor_A.shape}\nShape of Tensor-B: {Tensor_B.shape}')
print(f'Transpose of Tensor-B: {Tensor_B.T}\nShape of Tensor-B Transpose: {Tensor_A.T.shape}')
print(f'Dot Product of Tensor-A and Transpose of Tensor-B: {torch.matmul(Tensor_A, Tensor_B.T)}')
print(f'Transpose of Tensor-A: {Tensor_A.T}\nShape of Tensor-A Transpose {Tensor_A.T.shape}')
print(f'Dot Product of Tensor-A Transpose and Tensor-B: {torch.matmul(Tensor_A.T, Tensor_B)}')

Tensor-A: tensor([[1, 2],
        [3, 4],
        [5, 6]])
Tensor-B: tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])
Shape of Tensor-A: torch.Size([3, 2])
Shape of Tensor-B: torch.Size([3, 2])
Transpose of Tensor-B: tensor([[ 7,  9, 11],
        [ 8, 10, 12]])
Shape of Tensor-B Transpose: torch.Size([2, 3])
Dot Product of Tensor-A and Transpose of Tensor-B: tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])
Transpose of Tensor-A: tensor([[1, 3, 5],
        [2, 4, 6]])
Shape of Tensor-A Transpose torch.Size([2, 3])
Dot Product of Tensor-A Transpose and Tensor-B: tensor([[ 89,  98],
        [116, 128]])


**Tensor Aggregation operations**

1. min
2. max
3. mean

In [62]:
Tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
torch.max(Tensor)

tensor(6)

In [63]:
torch.min(Tensor)

tensor(1)

In [64]:
torch.sum(Tensor)

tensor(21)

In [65]:
#Now checking if all these operations also work with the same tensor but with long data type
Tensor = Tensor.type(dtype = torch.long)
torch.max(Tensor)

tensor(6)

In [66]:
Tensor.dtype

torch.int64

In [67]:
torch.mean(Tensor)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

**Note: torch.mean works only with float and complex dtype**

In [ ]:
torch.mean(Tensor.type(dtype = torch.float32))

In [ ]:
torch.sum(Tensor)

In [68]:
Tensor.sum()

tensor(21)

**Note: Both Tensor.sum() & torch.sum(Tensor) work and they return the sum of all the elements in the tensor**

In [69]:
torch.argmax(Tensor)

tensor(5)

In [70]:
torch.argmin(Tensor)

tensor(0)

In [71]:
Tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

**Note: Both Tensor.argmax() or Torch.argmin() & torch.argmin(Tensor) or torch.argmax(Tensor) work ,and they return the index or position of the largest and the smallest elements in a tensor**

In [72]:
Tensor.argmin()

tensor(0)

In [73]:
Tensor.argmax()

tensor(5)

**Reshaping, viweing and stacking Tensors**

1. **Reshaping:** Converting the shape of a tensor to a desired one
2. **View:** Return a view of inputs tensor of certain shape but still keeps the same original tensor in the memory
3. **Stacking:** Combining multiple tensors on top of each other (vstack) or side-by-side (hstack)
4. **Squeeze:** Removes all the 1 dimensions from the tensor
5. **Unsqueeze:** Adds a 1 dimension to the tensor
6. **Permute:** Return a view of the input with dimensions permuted (swapped) in a certain way

In [74]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [75]:
#Adding an extra dimension
x = x.reshape(1, 9)
x

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [76]:
x.shape

torch.Size([1, 9])

In [77]:
#Changing the view of tensor
z = x.view(9, 1)
z

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [78]:
z.shape

torch.Size([9, 1])

**Note: Here z shares the same memory as x and both aren't separate tensors. Therefore changing any element or anything in x or z brings about the same change in the other**

**Stacking Tensors**

In [79]:
x_stacked = torch.stack([x, x, x, x])
x_stacked

tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]],

        [[1., 2., 3., 4., 5., 6., 7., 8., 9.]],

        [[1., 2., 3., 4., 5., 6., 7., 8., 9.]],

        [[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])

**Note: By default torch.stack takes a list of tensors as arguments and default is 0 which results in stacking along axis = 0 which is hstack (horizontal stacking)**

In [80]:
x_stacked_1 = torch.stack([x, x, x, x], dim = 1)
x_stacked_1

tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [81]:
x_stacked_1.shape

torch.Size([1, 4, 9])

In [82]:
x_stacked.shape

torch.Size([4, 1, 9])

**Squeezing and unsqueezing tensors**

In [83]:
x

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [84]:
x.shape

torch.Size([1, 9])

In [85]:
torch.squeeze(x).shape

torch.Size([9])

In [86]:
torch.unsqueeze(x, dim = 1).shape

torch.Size([1, 1, 9])

**unsqueeze requires dim as an argument to determine where to add the next dimension**

In [87]:
x.shape

torch.Size([1, 9])

In [88]:
x = torch.squeeze(x)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [89]:
x.shape

torch.Size([9])

In [90]:
y = torch.unsqueeze(x, dim = 0)
y

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [91]:
y.shape

torch.Size([1, 9])

In [92]:
z = torch.unsqueeze(x, dim = 1)
z, z.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

**Note: torch.unsqueeze(dim = 0) adds 1 dim in the beginning while torch.unsqueeze(dim = 1) adds 1 dim at the end of the tensor**

In [93]:
#Torch.permute rearranges the dimensions of the tensors in a specified order
tensor  = torch.rand(size = (3, 224, 224))
tensor

tensor([[[0.9872, 0.8641, 0.2094,  ..., 0.7278, 0.2570, 0.3022],
         [0.0443, 0.7787, 0.9490,  ..., 0.5902, 0.1355, 0.4092],
         [0.5216, 0.5685, 0.5044,  ..., 0.8061, 0.0529, 0.8200],
         ...,
         [0.2187, 0.5150, 0.5509,  ..., 0.4603, 0.9346, 0.7710],
         [0.2504, 0.0635, 0.3310,  ..., 0.9923, 0.4690, 0.8146],
         [0.6913, 0.8472, 0.8371,  ..., 0.0650, 0.2138, 0.1161]],

        [[0.3264, 0.7273, 0.0493,  ..., 0.7387, 0.5815, 0.9115],
         [0.0644, 0.9226, 0.6776,  ..., 0.3511, 0.4185, 0.8914],
         [0.4582, 0.3806, 0.9886,  ..., 0.3879, 0.3589, 0.5774],
         ...,
         [0.0430, 0.4825, 0.7102,  ..., 0.8772, 0.7297, 0.5583],
         [0.3240, 0.9784, 0.7885,  ..., 0.5130, 0.9675, 0.8626],
         [0.6368, 0.2346, 0.0738,  ..., 0.9598, 0.7536, 0.1121]],

        [[0.2939, 0.5167, 0.0720,  ..., 0.6451, 0.8537, 0.4399],
         [0.8746, 0.1901, 0.7924,  ..., 0.3763, 0.6313, 0.0903],
         [0.3738, 0.8118, 0.2815,  ..., 0.5643, 0.5916, 0.

In [94]:
img_tensor = torch.permute(tensor, (1, 2, 0))
img_tensor

tensor([[[0.9872, 0.3264, 0.2939],
         [0.8641, 0.7273, 0.5167],
         [0.2094, 0.0493, 0.0720],
         ...,
         [0.7278, 0.7387, 0.6451],
         [0.2570, 0.5815, 0.8537],
         [0.3022, 0.9115, 0.4399]],

        [[0.0443, 0.0644, 0.8746],
         [0.7787, 0.9226, 0.1901],
         [0.9490, 0.6776, 0.7924],
         ...,
         [0.5902, 0.3511, 0.3763],
         [0.1355, 0.4185, 0.6313],
         [0.4092, 0.8914, 0.0903]],

        [[0.5216, 0.4582, 0.3738],
         [0.5685, 0.3806, 0.8118],
         [0.5044, 0.9886, 0.2815],
         ...,
         [0.8061, 0.3879, 0.5643],
         [0.0529, 0.3589, 0.5916],
         [0.8200, 0.5774, 0.2566]],

        ...,

        [[0.2187, 0.0430, 0.9849],
         [0.5150, 0.4825, 0.9206],
         [0.5509, 0.7102, 0.1274],
         ...,
         [0.4603, 0.8772, 0.4234],
         [0.9346, 0.7297, 0.7044],
         [0.7710, 0.5583, 0.2494]],

        [[0.2504, 0.3240, 0.4673],
         [0.0635, 0.9784, 0.1768],
         [0.

In [95]:
img_tensor.shape, tensor.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [96]:
img_tensor = torch.permute(tensor, (2, 1, 0))
img_tensor, img_tensor.shape

(tensor([[[0.9872, 0.3264, 0.2939],
          [0.0443, 0.0644, 0.8746],
          [0.5216, 0.4582, 0.3738],
          ...,
          [0.2187, 0.0430, 0.9849],
          [0.2504, 0.3240, 0.4673],
          [0.6913, 0.6368, 0.6515]],
 
         [[0.8641, 0.7273, 0.5167],
          [0.7787, 0.9226, 0.1901],
          [0.5685, 0.3806, 0.8118],
          ...,
          [0.5150, 0.4825, 0.9206],
          [0.0635, 0.9784, 0.1768],
          [0.8472, 0.2346, 0.8931]],
 
         [[0.2094, 0.0493, 0.0720],
          [0.9490, 0.6776, 0.7924],
          [0.5044, 0.9886, 0.2815],
          ...,
          [0.5509, 0.7102, 0.1274],
          [0.3310, 0.7885, 0.3881],
          [0.8371, 0.0738, 0.4930]],
 
         ...,
 
         [[0.7278, 0.7387, 0.6451],
          [0.5902, 0.3511, 0.3763],
          [0.8061, 0.3879, 0.5643],
          ...,
          [0.4603, 0.8772, 0.4234],
          [0.9923, 0.5130, 0.7794],
          [0.0650, 0.9598, 0.4116]],
 
         [[0.2570, 0.5815, 0.8537],
          [0

**Note: torch.permute() accepts input tensor and a tuple of order of the dimensions as arguments. For instance in the above example the original tensor has the shape (3, 224, 224) and img_tensor is given (1, 2, 0) as arguments which means dim in index-1 first, then the one in index-2 and finally dim in index-0 which gives the shape (224, 224, 3) to img_tensor**

In [97]:
tensor = torch.zeros(size = (3, 224, 224))

In [98]:
img_tensor

tensor([[[0.9872, 0.3264, 0.2939],
         [0.0443, 0.0644, 0.8746],
         [0.5216, 0.4582, 0.3738],
         ...,
         [0.2187, 0.0430, 0.9849],
         [0.2504, 0.3240, 0.4673],
         [0.6913, 0.6368, 0.6515]],

        [[0.8641, 0.7273, 0.5167],
         [0.7787, 0.9226, 0.1901],
         [0.5685, 0.3806, 0.8118],
         ...,
         [0.5150, 0.4825, 0.9206],
         [0.0635, 0.9784, 0.1768],
         [0.8472, 0.2346, 0.8931]],

        [[0.2094, 0.0493, 0.0720],
         [0.9490, 0.6776, 0.7924],
         [0.5044, 0.9886, 0.2815],
         ...,
         [0.5509, 0.7102, 0.1274],
         [0.3310, 0.7885, 0.3881],
         [0.8371, 0.0738, 0.4930]],

        ...,

        [[0.7278, 0.7387, 0.6451],
         [0.5902, 0.3511, 0.3763],
         [0.8061, 0.3879, 0.5643],
         ...,
         [0.4603, 0.8772, 0.4234],
         [0.9923, 0.5130, 0.7794],
         [0.0650, 0.9598, 0.4116]],

        [[0.2570, 0.5815, 0.8537],
         [0.1355, 0.4185, 0.6313],
         [0.

In [99]:
tensor

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

**Indexing on Tensors**

In [100]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [101]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [102]:
x[0][1]

tensor([4, 5, 6])

In [103]:
x[0][2][2]

tensor(9)

In [104]:
x[: , 0]

tensor([[1, 2, 3]])

In [105]:
x[: , :, 1]

tensor([[2, 5, 8]])

In [106]:
x[: , 1, 1]

tensor([5])

In [107]:
x[0, 0, : ]

tensor([1, 2, 3])

In [108]:
x[:, :, 2]

tensor([[3, 6, 9]])

**PyTorch Tensors & NumPy**

In [109]:
#NumPy array to a tensor
arr = np.arange(1.0, 8.0)
arr

array([1., 2., 3., 4., 5., 6., 7.])

In [110]:
type(arr)

numpy.ndarray

In [111]:
tensor = torch.tensor(arr)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [112]:
tensor = tensor.type(dtype = torch.float32)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.])

In [113]:
tensor.dtype

torch.float32

**Note: By default when we convert a numpy array to a tensor, the dtype will be float64 so we have to explicitly specify we need float32 dtype**

In [114]:
#Tensor to numpy array
t1 = torch.ones(size = (7, 1))
t1

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [115]:
array = t1.numpy()

In [116]:
array

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [117]:
array.dtype

dtype('float32')

In [118]:
type(array)

numpy.ndarray

**tensor.numpy() returns a numpy array of the tensor however the dtype of the numpy array will be the same as that of the original tensor**

**PyTorch Reproducibility**

seed can be used for reproducing the same randomness

In [119]:
# 2 Random Tensors
random_tensor_a = torch.rand(3, 4)
random_tensor_b = torch.rand(3, 4)

In [120]:
random_tensor_a == random_tensor_b

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [121]:
random_tensor_a

tensor([[0.4296, 0.0988, 0.2124, 0.5478],
        [0.9780, 0.9311, 0.3424, 0.3712],
        [0.1439, 0.2887, 0.5100, 0.5369]])

In [122]:
random_tensor_b

tensor([[0.8134, 0.8308, 0.1883, 0.7106],
        [0.1701, 0.6126, 0.1710, 0.2162],
        [0.2400, 0.3017, 0.2075, 0.8195]])

**Note: You can clearly see that none of the elements are the same in both the tensors**

In [125]:
#Making reproducible random tensors
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3, 4)
random_tensor_d = torch.rand(3, 4)

print(random_tensor_c == random_tensor_d)
print(f'{random_tensor_c}\n{random_tensor_d}')


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])


**Note: torch.manual_seed(value) is used for setting pseudorandom values i.e. reproduce the same random values**

**Running PyTorch objects and Tensors on Nvidia GPUs**

**Setting up Device Agnostic Code**

In [138]:
device = 'cuda' if cuda.is_available() else 'cpu'

In [139]:
device

'cuda'

**Note: If the GPU is available we're setting device as CUDA else we're using CPU**

In [140]:
#Checking the number of GPUs
cuda.device_count()

1

**Setting up Device Agnostic Code and loading the Tensors on and off the GPU**

In [141]:
tensor = torch.tensor([1, 2, 3, 4, 5])
print(f'Tensor: {tensor}\nDevice: {tensor.device}')

Tensor: tensor([1, 2, 3, 4, 5])
Device: cpu


**Note: tensor.device gives the device on which the tensor is stored. By default it is stored on CPU. tensor. tensor.to('cuda') is used for loading it on the GPU**

In [142]:
tensor.to(device)
print(f'Tensor: {tensor}\nDevice: {tensor.device}')

Tensor: tensor([1, 2, 3, 4, 5])
Device: cpu


In [143]:
tensor_on_gpu = tensor.to(device)
print(f'Tensor: {tensor}\nDevice: {tensor_on_gpu.device}')

Tensor: tensor([1, 2, 3, 4, 5])
Device: cuda:0


**Note: Just tensor.to(device) doesn't place it on the GPU. It has to be assigned to a tensor (more like creating a copy of hte same tensor and saving it on GPU).**

In [144]:
tensor_on_gpu.device

device(type='cuda', index=0)

In [145]:
#Converting the tensor to a numpy array
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Note: Once a Tensor has been moved to a GPU, it can't be converted back to a numpy array. It has to be moved to the CPU before doing that.**

In [146]:
tensor_on_gpu = tensor_on_gpu.to('cpu')

In [147]:
tensor_on_gpu.device

device(type='cpu')

In [148]:
tensor_on_gpu.numpy()

array([1, 2, 3, 4, 5])

**tensor.cpu() also places the tensor on the CPU**